### ISSUE TITLE
Update Github Issue Template Workflow

### ISSUE THREAD

**Issue by rafayet-monon** [nimblehq/git-template#8]
## Feature request

Currently, this repo has the [older version](https://github.com/nimblehq/git-template/blob/master/.github/ISSUE_TEMPLATE.md) of the issue template workflow. As Github introduced the [new issue template workflow](https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) we can update to a newer version.

We can create [different templates](https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates) for a feature and bug reports or we can create a generic and custom template as we have currently in this [repo](https://github.com/nimblehq/git-template/blob/master/.github/ISSUE_TEMPLATE.md). Refer to the image below, when templates are added users can select a template and open their issue respecting the template.

<img width="1168" alt="Screenshot 2020-09-09 at 12 51 25 PM" src="https://user-images.githubusercontent.com/14927672/92564567-30c08f00-f29b-11ea-94d1-c20b95c5f755.png">

Similar type of examples can be found at [Spree](https://github.com/spree/spree/issues/new/choose) when opening an issue.

**Comment by olivierobert** [comment]
@rafayet-monon You can have a go at it and open a PR for it. You can probably follow Compass: https://github.com/nimblehq/compass/tree/development/.github/ISSUE_TEMPLATE

**Comment by byhbt** [comment]
Hi!

I re-open this issue because we are using this git template in some projects, the Issue Template becomes quite handy when we open a new issue. However, I found that we have some limitation:

Currently, we have 2 kinds of issue:
- _Bug Report_: Report a bug
- _Feature_: Request a new feature

I think we can add one more template type:
- _Chore_: for proposing the minor change request, not as big as the Feature.

For example: update text, update README, add `.editorconfig`


![Screen Shot 2021-03-10 at 11 12 23 AM](https://user-images.githubusercontent.com/948856/110575493-87971a80-8191-11eb-9ca0-5b6f3fbf0b49.png)

**Comment by olivierobert** [comment]
@byhbt Indeed, adding a chore issue could be a good addition.

In terms of process, having a new issue as **a feature request** would be better than re-opening an already closed issue. This issue was to include different types of issues. Hence the implementation in #9 covered the basic needs. Now we need to iterate on it by adding more issue type which is a new feature.

**Comment by byhbt** [comment]
yes @olivierobert !

I will create a new feature request.
